name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # https://crontab.guru/every-week

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    if: github.event.commits[0].author.name != 'github-actions[bot]'
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
      - name: "Update schemes"
        uses: "tinted-theming/tinted-builder-rust@v0.9.5"
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: Build colors"
          branch: ${{ github.head_ref }}
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
